### ISSUE TITLE
Fix document links in https://www.oasis-open.org/wp-admin/post.php?post=4962&action=edit

### ISSUE THREAD

**Issue by chet-ensign** [oasis-dev/oasis-new-website#103]
Reported by Mary Beth. The post does not show the contents of the Document links box but they display correctly online. This ticket is to fix the Document links content to eliminate the possibility of a data corruption problem. 

Clarification: these are standards entries. When editing them, the text of links to documents doesn't display. However, when they are pulled up online, everything is there.

**Comment by chet-ensign** [comment]
Same problem with https://www.oasis-open.org/standard/wssv1-1-1/?preview_id=4961&preview_nonce=b876720f0f&preview=true

**Comment by chet-ensign** [comment]
Same problem with https://www.oasis-open.org/wp-admin/post.php?post=4965&action=edit

**Comment by chet-ensign** [comment]
Than recommends holding off edits until they can troubleshoot/debug.

**Comment by chet-ensign** [comment]
Opened #263 in HumanMade list to track fixing this.

**Comment by chet-ensign** [comment]
Fixed in staging but hasn't been pushed to production yet. Take that up when we start maintenance in April.

**Comment by chet-ensign** [comment]
HM has a ticket for this and Than has a solution. It will be addressed under maintenance.

**Comment by OASIS-OP-Admin** [comment]
HM noted that this looks like a problem with the HTML in the custom blocks they created. Attempting to fix risks corrupting the data. They could address by changing from a custom type to simple posts but we would lose the ability to export specific components of the standard data. 

Since this might allow us to export cite as blocks and create a citation guide for OASIS Standards, I said we'd leave it as is. 

So I'll go ahead and close this ticket with no action.
