### ISSUE TITLE
Generate link to filtered view of Projects

### ISSUE THREAD

**Issue by CarolGeyer** [oasis-dev/oasis-new-website#97]
Is there a way we can get a link to, for example, all the Projects with the "Privacy" Technology tag? 

This would be really useful when we're pitching a new project, and the proposer asks, "What other privacy projects do you have?" Of course, we can always tell them to go to /projects and filter on "privacy", but it would be great if we could provide the direct URL.

I think Scott knows the answer to this--not sure.

**Comment by chet-ensign** [comment]
@scottmcgrath - on this request from @carol - 

When I use the url https://www.oasis-open.org/projects-committees?filter-committee-status=active - it filters the projects for those that are active. 

However, when I try https://www.oasis-open.org/projects-committees?filter-technology-area=security - it does nothing. Just opens up the page of projects. 

Do you know if this is because the filter isn't 'technology-area'?

**Comment by OASIS-OP-Admin** [comment]
Thanks to Joeleen at HM. I was *this* close. The url is https://www.oasis-open.org/projects-committees/?filter-technology=security. I have to find out the filter name for privacy & test out the others but so far, using the lowercase filter name works.

**Comment by OASIS-OP-Admin** [comment]
To find the word to use for any given Technology Area, go to the WP dashboard, go down to the Projects & Committees section, and click on Technology Areas below it. The TAs will be listed. Click on any given one and then find its slug. For example, Privacy/Identity is privid. And indeed, https://www.oasis-open.org/projects-committees/?filter-technology=privid filters for those projects.

**Comment by OASIS-OP-Admin** [comment]
The question being answered, I'm closing this ticket.
